from models.net.resnet import resnet18
from models.net.resnet import resnet34
from models.net.resnet import resnet50
from models.net.mobilenet import mobilenet
from models.net.shufflenet import shufflenet
from models.net.mobilenetv2 import mobilenetv2
from models.net.senet import *
from models.net.ghostnet import ghostnet
from models.net.mobilenetv3 import mobilenetv3